### ISSUE TITLE
pushd with no popd in build-jedi-cache.sh

### ISSUE THREAD

**Issue by realh** [strycore/fakegir#17]
I noticed build-jedi-cache.sh was printing $JEDI_PATH multiple times in a row and found that it has the line 
`pushd $JEDI_PATH`
in a loop with no corresponding popd. I'm not sure whether it needs that pushd at all, so I just added `popd` before the loop's `done` and it seems to be working fine minus the extra 'noise'.

**Comment by strycore** [comment]
Thanks, I added that popd (and also made the output silent). I'm not sure that pushd is needed as well, @kassick is it here for a reason?

**Comment by kassick** [comment]
@strycore I can't see any good reason for the pushd -- I probably was sleepy when I did that, or paranoid that cwd would be different from the script's path or something

**Comment by strycore** [comment]
Ok, I'll remove it then :)
