### ISSUE TITLE
Error while parsing gir files

### ISSUE THREAD

**Issue by Viterzgir** [strycore/fakegir#18]
Parsing /usr/share/gir-1.0/Gdk-3.0.gir
Parsing /usr/share/gir-1.0/JavaScriptCore-1.0.gir
Traceback (most recent call last):
  File "./fakegir.py", line 400, in <module>
    generate_fakegir()
  File "./fakegir.py", line 390, in generate_fakegir
    for module_name, gir_file, gir_path in iter_girs():
  File "./fakegir.py", line 372, in iter_girs
    module_name = gir_file[:gir_file.index('-')]
ValueError: substring not found

**Comment by kastixx** [comment]
That's strange. Please check out the latest commit a9e1dc7c26e38fa69dbbf59dbabdbd9d7f9b5ee5. The script won't fail completely if it stumbles upon a file without dashes but a warning will be shown about every such file.

**Comment by strycore** [comment]
Marking as fixed.
