### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 422619: ordinal not in range(128)

### ISSUE THREAD

**Issue by ilyazzz** [strycore/fakegir#21]
I once used fakegir to get PyGObject completions work in vim with YCM, it worked fine. Now after reinstall of Arch Linux I'm getting an error when running fakegir.py:
`Parsing /usr/share/gir-1.0/Secret-1.gir
Parsing /usr/share/gir-1.0/Atk-1.0.gir
Traceback (most recent call last):
  File "./fakegir.py", line 420, in <module>
    generate_fakegir()
  File "./fakegir.py", line 412, in generate_fakegir
    fakegir_content = parse_gir(gir_path)
  File "./fakegir.py", line 366, in parse_gir
    content = open(gir_path).read()
  File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 422619: ordinal not in range(128)
`
P.S. My first time opening an issue on github, so idk how to make these logs's lines look better.

**Comment by kastixx** [comment]
Looks strange. Can you upload a copy of your `/usr/share/gir-1.0/Atk-1.0.gir` file somewhere?

> My first time opening an issue on github, so idk how to make these logs's lines look better.

You can place lines with three backticks (\`\`\`) before and after your log fragment:

\`\`\`
```
Parsing /usr/share/gir-1.0/Secret-1.gir
Parsing /usr/share/gir-1.0/Atk-1.0.gir
Traceback (most recent call last):
  File "./fakegir.py", line 420, in <module>
    generate_fakegir()
  File "./fakegir.py", line 412, in generate_fakegir
    fakegir_content = parse_gir(gir_path)
  File "./fakegir.py", line 366, in parse_gir
    content = open(gir_path).read()
  File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 422619: ordinal not in range(128)
```
\`\`\`

**Comment by ilyazzz** [comment]
Sure: https://drive.google.com/open?id=1PhWfnylneFBeHMlHXdNblMoJbla_Y4DS

**Comment by kastixx** [comment]
Could you do
```
git fetch
git checkout test-issue21
```
and try running `fakegir.py` again?

**Comment by ilyazzz** [comment]
Wow thank you, that fixed the issue!

**Comment by kastixx** [comment]
No problem! Switch back to master please, I've merged that patch.
